# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('host_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('modify_people', models.CharField(editable=False, max_length=30, verbose_name='修改人')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU(核)')),
                ('memory', models.IntegerField(blank=True, null=True, verbose_name='内存(G)')),
                ('storage', models.IntegerField(blank=True, null=True, verbose_name='硬盘(G)')),
                ('start_time', models.DateField(default=django.utils.timezone.now, max_length=20, verbose_name='申请日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='是否永久使用')),
                ('use', models.TextField(blank=True)),
                ('maintainer', models.CharField(max_length=30, verbose_name='维护人/组')),
                ('location', models.CharField(choices=[('理想公司测试机房', '理想公司测试机房'), ('生产机房', '生产机房')], max_length=30, verbose_name='所在机房')),
                ('os', models.CharField(blank=True, choices=[('Windows', (('WindowsServer2008', 'WindowsServer2008'), ('Windows7', 'Windows7'))), ('Linux', (('Centos6', 'Centos6'), ('Centos7', 'Centos7'), ('RedHat6', 'RedHat6'), ('RedHat7', 'RedHat7'), ('Suse', 'Suse')))], max_length=20, verbose_name='操作系统')),
            ],
        ),
        migrations.CreateModel(
            name='IP_Resource',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True, verbose_name='IP地址')),
                ('bin_ip', models.BigIntegerField(editable=False)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bin_ip'],
            },
        ),
        migrations.AddField(
            model_name='host_info',
            name='ip_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.IP_Resource', verbose_name='IP地址'),
        ),
    ]
