# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mail_senthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='sent_count',
        ),
        migrations.AddField(
            model_name='mail',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='是否发送'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_date',
            field=models.DateField(verbose_name='下一次发送日期'),
        ),
        migrations.AlterField(
            model_name='senthistory',
            name='sent_date',
            field=models.DateField(auto_now_add=True, verbose_name='发送日期'),
        ),
    ]
