# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171113_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Host_info', verbose_name='主机'),
        ),
    ]
