# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_host_info_tmp_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_info',
            name='maintainer',
        ),
    ]
