# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_host_info_maintainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_info',
            old_name='tmp_m',
            new_name='maintainer',
        ),
    ]
