# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171114_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='维护人/组'),
        ),
    ]
