# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171114_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senthistory',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Host_info', verbose_name='主机'),
        ),
    ]
