# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171114_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name_chinese', models.CharField(max_length=100, verbose_name='项目中文名称')),
                ('proj_name_english', models.CharField(max_length=100, verbose_name='项目英文名称')),
                ('proj_property', models.CharField(choices=[('project', '项目'), ('production', '产品')], max_length=30, verbose_name='项目性质')),
                ('center', models.CharField(max_length=50, verbose_name='中心')),
                ('pm', models.CharField(max_length=50, verbose_name='项目经理')),
                ('tm', models.CharField(max_length=50, verbose_name='技术经理')),
                ('dev', models.CharField(max_length=300, verbose_name='开发人员')),
                ('test_manager', models.CharField(max_length=50, verbose_name='测试经理')),
                ('test', models.CharField(max_length=300, verbose_name='测试人员')),
            ],
        ),
    ]
