# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_svn'),
    ]

    operations = [
        migrations.AddField(
            model_name='svn',
            name='applier',
            field=models.CharField(default='null', max_length=100, verbose_name='申请人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='svn',
            name='apply_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='svn',
            name='center',
            field=models.CharField(choices=[('开发交付一中心', '开发交付一中心'), ('开发交付二中心', '开发交付二中心'), ('技术创新中心', '技术创新中心'), ('支撑拓展中心', '支撑拓展中心')], max_length=50, verbose_name='中心'),
        ),
        migrations.AlterField(
            model_name='svn',
            name='proj_property',
            field=models.CharField(choices=[('project', '项目'), ('production', '产品')], default='project', max_length=30, verbose_name='项目性质'),
        ),
        migrations.AlterField(
            model_name='svn',
            name='test',
            field=models.CharField(blank=True, max_length=300, verbose_name='测试人员'),
        ),
    ]
