# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171211_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host_info',
            options={'verbose_name': '主机(虚拟机)资源', 'verbose_name_plural': '主机(虚拟机)资源'},
        ),
        migrations.AlterModelOptions(
            name='ip_resource',
            options={'ordering': ['bin_ip'], 'verbose_name': 'IP地址资源', 'verbose_name_plural': 'IP地址资源'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': '主机到期邮件', 'verbose_name_plural': '主机到期邮件'},
        ),
        migrations.AlterModelOptions(
            name='senthistory',
            options={'verbose_name': '已发主机到期邮件', 'verbose_name_plural': '已发主机到期邮件'},
        ),
        migrations.AlterModelOptions(
            name='svn',
            options={'verbose_name': 'SVN', 'verbose_name_plural': 'SVN'},
        ),
        migrations.AlterField(
            model_name='svn',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='svn',
            name='proj_property',
            field=models.CharField(choices=[('项目', '项目'), ('产品', '产品')], default='project', max_length=30, verbose_name='项目性质'),
        ),
    ]
